"""Shared models for the Phase 9 LLM helper layer."""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Generic, Literal, Protocol, TypeVar

from pydantic import BaseModel, Field

DEFAULT_OPENAI_MODEL = "gpt-5.4-mini"
ApiMode = Literal["responses", "chat-completions"]
OutputT = TypeVar("OutputT", bound=BaseModel)
_ENV_KEY_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_ENDPOINT_SUFFIXES = ("/responses", "/chat/completions", "/completions", "/models")


class LLMInputError(ValueError):
    """Raised when LLM input, configuration, or prompt files are invalid."""


class LLMServiceError(RuntimeError):
    """Raised when the OpenAI SDK call fails or returns an unusable response."""


class OpenAISettings(BaseModel):
    """Runtime settings for OpenAI SDK calls."""

    model: str = DEFAULT_OPENAI_MODEL
    base_url: str | None = None
    api_mode: ApiMode = "responses"
    api_key_env: str | None = None
    reasoning_effort: str | None = None
    enable_thinking: bool = False
    timeout_seconds: float = 60.0
    max_output_tokens: int = 4000
    store: bool = False

    @classmethod
    def from_env(
        cls,
        *,
        model: str | None = None,
        base_url: str | None = None,
        api_mode: ApiMode | None = None,
        api_key_env: str | None = None,
        reasoning_effort: str | None = None,
        enable_thinking: bool | None = None,
        timeout_seconds: float = 60.0,
        max_output_tokens: int = 4000,
        store: bool = False,
    ) -> OpenAISettings:
        """Build settings using CLI overrides first, then environment defaults."""
        load_dotenv_if_present()
        resolved_model = (
            _clean_optional(model)
            or _clean_optional(os.environ.get("CHEMWF_OPENAI_MODEL"))
            or DEFAULT_OPENAI_MODEL
        )
        resolved_base_url = (
            _clean_optional(base_url)
            or _clean_optional(os.environ.get("OPENAI_BASE_URL"))
            or _clean_optional(os.environ.get("CHEMWF_OPENAI_BASE_URL"))
        )
        validate_openai_base_url(resolved_base_url)
        resolved_api_mode = (
            api_mode
            or _parse_api_mode(os.environ.get("CHEMWF_OPENAI_API_MODE"))
            or "responses"
        )
        resolved_api_key_env = (
            _clean_optional(api_key_env)
            or _clean_optional(os.environ.get("CHEMWF_OPENAI_API_KEY_ENV"))
            or _default_api_key_env(resolved_base_url)
        )
        resolved_reasoning_effort = _clean_optional(reasoning_effort) or _clean_optional(
            os.environ.get("CHEMWF_OPENAI_REASONING_EFFORT")
        )
        resolved_enable_thinking = (
            enable_thinking
            if enable_thinking is not None
            else _parse_bool(os.environ.get("CHEMWF_OPENAI_ENABLE_THINKING"))
        )
        return cls(
            model=resolved_model,
            base_url=resolved_base_url,
            api_mode=resolved_api_mode,
            api_key_env=resolved_api_key_env,
            reasoning_effort=resolved_reasoning_effort,
            enable_thinking=resolved_enable_thinking,
            timeout_seconds=timeout_seconds,
            max_output_tokens=max_output_tokens,
            store=store,
        )


class LLMWarning(BaseModel):
    """A warning produced by the LLM layer or post-generation validator."""

    code: str
    message: str
    severity: Literal["info", "warning", "risk"] = "warning"


class LLMRunMetadata(BaseModel):
    """Metadata stored alongside an LLM run for traceability."""

    task: str
    model: str
    prompt_version: str
    created_at: datetime
    input_hash: str
    request_id: str | None = None


class ExperimentRecordDraft(BaseModel):
    """Schema-valid draft experiment record generated by the LLM."""

    status: Literal["draft"] = "draft"
    title: str
    markdown: str
    warnings: list[LLMWarning] = Field(default_factory=list)
    source_fields_used: list[str] = Field(default_factory=list)
    unsupported_claims: list[str] = Field(default_factory=list)


class AssignmentSummaryDraft(BaseModel):
    """Schema-valid draft summary for rule-based assignment review."""

    status: Literal["draft"] = "draft"
    summary_markdown: str
    unresolved_items: list[str] = Field(default_factory=list)
    review_checklist: list[str] = Field(default_factory=list)
    warnings: list[LLMWarning] = Field(default_factory=list)


@dataclass(frozen=True)
class PromptTemplate:
    """Prompt text and version loaded from `prompts/`."""

    name: str
    version: str
    text: str
    path: Path


@dataclass(frozen=True)
class StructuredLLMResult(Generic[OutputT]):
    """A parsed LLM output with the input and metadata needed for run logging."""

    output: OutputT
    metadata: LLMRunMetadata
    input_payload: dict[str, Any]
    prompt: PromptTemplate


class LLMClientProtocol(Protocol):
    """Small protocol for fakeable structured-output clients."""

    def parse_structured(
        self,
        *,
        settings: OpenAISettings,
        instructions: str,
        input_text: str,
        output_model: type[OutputT],
        metadata: dict[str, str],
    ) -> tuple[OutputT, str | None]:
        """Return a parsed Pydantic model plus optional request id."""


def load_dotenv_if_present(env_file: str | Path | None = None) -> Path | None:
    """Load a local `.env` file without overriding existing environment variables.

    Resolution order:
    1. Explicit `env_file` argument
    2. `CHEMWF_ENV_FILE`
    3. Nearest `.env` found by walking from the current working directory upward

    This intentionally implements only the small dotenv subset needed for credentials and endpoint
    settings: `KEY=value`, optional `export KEY=value`, quoted values, blank lines, and comments.
    """
    path = _resolve_env_file(env_file)
    if path is None or not path.exists() or not path.is_file():
        return None

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        parsed = _parse_env_line(raw_line)
        if parsed is None:
            continue
        key, value = parsed
        os.environ.setdefault(key, value)
    return path


def validate_openai_base_url(base_url: str | None) -> None:
    """Reject common endpoint URLs that should not be passed as SDK `base_url`."""
    cleaned = _clean_optional(base_url)
    if cleaned is None:
        return
    normalized = cleaned.rstrip("/").lower()
    if normalized.endswith(_ENDPOINT_SUFFIXES):
        raise LLMInputError(
            "`base_url` 应该是 API 根路径，而不是完整 endpoint。"
            "例如使用 `https://.../v1`，不要使用 "
            "`https://.../v1/responses` 或 `https://.../v1/chat/completions`。"
        )


def resolve_api_key(settings: OpenAISettings) -> str | None:
    """Resolve the API key from the configured env var, with safe fallbacks."""
    load_dotenv_if_present()
    candidates = [settings.api_key_env, "OPENAI_API_KEY", "DEEPSEEK_API_KEY"]
    seen: set[str] = set()
    for key_name in candidates:
        if not key_name or key_name in seen:
            continue
        seen.add(key_name)
        value = _clean_optional(os.environ.get(key_name))
        if value:
            return value
    return None


def _clean_optional(value: str | None) -> str | None:
    if value is None:
        return None
    stripped = value.strip()
    return stripped or None


def _default_api_key_env(base_url: str | None) -> str:
    cleaned = (base_url or "").lower()
    if "deepseek.com" in cleaned:
        return "DEEPSEEK_API_KEY"
    return "OPENAI_API_KEY"


def _parse_api_mode(value: str | None) -> ApiMode | None:
    cleaned = _clean_optional(value)
    if cleaned is None:
        return None
    if cleaned not in ("responses", "chat-completions"):
        raise LLMInputError(
            "CHEMWF_OPENAI_API_MODE 只支持 `responses` 或 `chat-completions`，"
            f"收到 {cleaned!r}。"
        )
    return cleaned


def _parse_bool(value: str | None) -> bool:
    cleaned = _clean_optional(value)
    if cleaned is None:
        return False
    return cleaned.lower() in {"1", "true", "yes", "y", "on", "enabled", "enable"}


def _resolve_env_file(env_file: str | Path | None) -> Path | None:
    explicit = env_file or _clean_optional(os.environ.get("CHEMWF_ENV_FILE"))
    if explicit is not None:
        return Path(explicit).expanduser()

    cwd = Path.cwd().resolve()
    for directory in (cwd, *cwd.parents):
        candidate = directory / ".env"
        if candidate.exists():
            return candidate
    return None


def _parse_env_line(raw_line: str) -> tuple[str, str] | None:
    line = raw_line.strip()
    if not line or line.startswith("#"):
        return None
    if line.startswith("export "):
        line = line.removeprefix("export ").strip()
    if "=" not in line:
        return None

    key, raw_value = line.split("=", 1)
    key = key.strip()
    if not _ENV_KEY_RE.match(key):
        return None

    value = raw_value.strip()
    value = value[1:-1] if _is_quoted(value) else _strip_inline_comment(value).strip()
    return key, value


def _is_quoted(value: str) -> bool:
    return len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}


def _strip_inline_comment(value: str) -> str:
    for marker in (" #", "\t#"):
        if marker in value:
            return value.split(marker, 1)[0]
    return value
